### ISSUE TITLE
Cannot `az --version` without dev-python/pip

### ISSUE THREAD

**Issue by au-phiware** [linuxunderground/gentoo.overlay#1]
Having just installed `net-misc/azure-cli-2.0.10::linuxunderground-overlay`, running `az --version` produces:

````
ImportError: No module named 'pip'
````

Installing `dev-python/pip-9.0.1-r1::gentoo` resolve the problem.

**Comment by linuxunderground** [comment]
Fixed with dev-python/azure-cli-core-2.0.11.

With USE flag vanilla, `az --version` displays original Microsoft listing of azure modules (using pip).
Otherwise, `az --version` displays a list of azure modules that comes from portage itself ! In this case, pip is not required.
