### ISSUE TITLE
Invalid atom in profiles/package.mask

### ISSUE THREAD

**Issue by hgoetzger** [linuxunderground/gentoo.overlay#2]
Salute,

looks like a typo:

```
q: Updating ebuild cache in /usr/portage ... 
--- Invalid atom in /var/lib/layman/linuxunderground-overlay/profiles/package.mask: =dev-python/azure-mgmt-compute-3.1.0_rc3.ebuild
```
Came in with https://github.com/linuxunderground/gentoo.overlay/commit/4192ab9a9303d32730b78e336100442eb825ee45#diff-32577b98f47a85235ad8b43fea1d65f4

Thanks & cheers

Heinrich

**Comment by mgorny** [comment]
This is causing the whole Gentoo CI infra to explode.

**Comment by linuxunderground** [comment]
Sorry.
Fixed

**Comment by hgoetzger** [comment]
Looks TippTopp, thanks for the quickFix!
