### ISSUE TITLE
Error while installing dev-python/azure-cli-telemetry

### ISSUE THREAD

**Issue by r7l** [linuxunderground/gentoo.overlay#3]
Thanks allot for providing all those packages for **azure-cli**. When installing it, if failed on **dev-python/azure-cli-telemetry**, with the following error:

    rm: cannot remove '/var/tmp/portage/dev-python/azure-cli-telemetry- 
    1.0.0/image/usr/lib64/python2.7/site-packages/azure/__pycache__': No such file or directory
    * ERROR: dev-python/azure-cli-telemetry-1.0.0::linuxunderground-overlay failed (install phase):
    *   (no error message)`

... later on ...

    * The specific snippet of code:
    *       rm -r "${ED}${PYTHON_SITEDIR}/azure/__pycache__" || die;

Is there any way to fix this?

**Comment by linuxunderground** [comment]
Can you attach output of emerge --info
I suspect that your problem is related to the portage version you use...

I must also admit that I no longer test installation with python 2.7.

**Comment by r7l** [comment]
Sorry for not getting back to the topic earlier. At first, i've moved on with this, in an Ubuntu VM and later on, we've decided to not use Azure at all, for a number of other reasons that are not related to Gentoo. Thanks anyways for your help and for offering azure-cli. If i ever give this another retry, i will just do it without Python 2.7.

**Comment by linuxunderground** [comment]
not reproducible with current portage
