### ISSUE TITLE
app-emulation/comcom32-bin-0.1_p201912030201 is fatally outdated

### ISSUE THREAD

**Issue by 0n-s** [linuxunderground/gentoo.overlay#5]
This ebuild's version is so old that all the URLs in SRC_URI give 404s.

This, notably, prevents app-emulation/dosemu2-9999 from building.

**Comment by 0n-s** [comment]
This seems to still be broken, as Launchpad seems to have changed its package compression format from xz to Zstd.

To fix, src_unpack should unpack `./data.tar.zst` instead.

**Comment by linuxunderground** [comment]
Fixed hopefully !

But it wasn't that easy: 
Compression is xz for x86 archive and zstd for amd64 archive and moreover unpack does not recognize zstd compression.

**Comment by 0n-s** [comment]
Hm, both of those issues are quite unexpected. Nevertheless, from my testing it is indeed fixed, yes. :)
